# Paths
export PATH=/usr/local/bin:$PATH

# Include configuration files
source $HOME/.config/env.sh

# Include modules
source $ZSH_DIR/modules/nvm.sh
source $ZSH_DIR/modules/git.sh
source $ZSH_DIR/modules/launchctl.sh
source $ZSH_DIR/modules/sql.sh
source $ZSH_DIR/modules/alias.sh

# Include plugins
plugins=(
    git
    docker
    history
    common-aliases
    aliases
    tig
    frontend-search # https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/frontend-search/README.md
)

source $ZSH_DIR/plugins/vcs.zsh
source $ZSH_DIR/plugins/prompt.zsh

source $ZSH_DIR/bin/ohmyzsh/oh-my-zsh.sh
source $ZSH_DIR/bin/zsh-autosuggestions/zsh-autosuggestions.zsh
